language: cpp
install:
  - cd ..
  - git clone https://github.com/cpputest/cpputest.git
  - cd cpputest
  - autoreconf . -i
  - ./configure
  - make
  - cd ../ardumower
Compiler: gcc
script: cd ArduMower_Test && SILENCE=" " make gcov
