os: linux
dist: bionic
language: cpp

jobs:
  include:
    - install:
        - cd ..
        - mkdir bin
        - curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
        - export PATH=$(pwd)/bin:$PATH
        - arduino-cli config init
        - arduino-cli core update-index
        - arduino-cli core install arduino:avr
        - cd ardumower
      script:
        - make all
    - install:
        - cd ..
        - git clone https://github.com/cpputest/cpputest.git
        - cd cpputest
        - autoreconf . -i
        - ./configure
        - make -j
        - cd ../ardumower/ArduMower_Test
      script: make -j gcov
