language: cpp
install:
  - cd ..
  - git clone https://github.com/cpputest/cpputest.git
  - cd cpputest/cpputest_build
  - autoreconf .. -i
  - cd ..
  - ./configure
  - make
  - cd ../ardumower
Compiler: gcc
script: cd ArduMower_Test && make gcov
